# dacho-example/Cargo.toml

[package]
name         = "dacho-example"
version      = "0.2.0"
rust-version = "1.80.1"
authors      = ["mochou-p"]
edition      = "2021"
description  = "Example game for dacho"
repository   = "https://github.com/mochou-p/dacho-example"
license      = "MIT OR Apache-2.0"
keywords     = ["dacho", "game", "example", "template", "3D"]
categories   = ["game-development", "games", "multimedia", "graphics", "rendering"]

[dependencies]
dacho = "0.2.0"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[lints.rust]
warnings = "deny"

[lints.clippy]
all      = "deny"
nursery  = "deny"
pedantic = "deny"

